#!/usr/bin/env python3
"""One-time, explicit editorial import from the preserved source records.

This is an authoring tool, never a build step. Its output is committed source.
"""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
catalog=json.loads((ROOT/'data/catalogo-curado.json').read_text())

# ASIN: stable id, group, selection role, intended use, documented interpretation,
# exclusion, conditional value judgement, alternative. No numeric ratings/prices.
COPY={
'B08KKBSDTY':('g335','headsets','Para silenciar o microfone com um gesto','Quem prefere um headset analógico com microfone que silencia ao levantar.', 'O mecanismo de levantar para silenciar é um diferencial prático frente a microfones destacáveis. O peso documentado de 240 g ajuda a comparar a construção, mas não prova conforto para todas as cabeças.', 'O microfone não é destacável e a conexão é com fio. Confira a entrada 3,5 mm do aparelho e o ajuste da faixa.', 'Compare com Havit e Cloud III pelo tipo de controle e conexão que você usará. Não pague mais apenas por um peso menor na ficha.', 'havit-h2002d'),
'B07JM7DR7K':('g502-hero','mouses','Para muitos comandos no mouse','Quem usa atalhos em jogos ou programas e quer mais botões acessíveis.', 'Os 11 botões programáveis oferecem uma razão para sair de um mouse compacto mais simples. Os pesos adicionais permitem alterar a massa; isso não o transforma em um ultraleve.', 'O corpo, os botões e o cabo precisam combinar com sua pegada. Não é a escolha para quem procura simplicidade máxima ou liberdade sem fio.', 'O adicional compensa quando os comandos extras substituem ações frequentes no teclado. Se você usa poucos botões, compare G203 e G305 primeiro.', 'g305'),
'B081P3Z565':('g213','teclados','Para layout brasileiro e controles de mídia','Quem quer teclado ABNT2 de tamanho completo com apoio de mãos integrado.', 'O layout brasileiro, os controles dedicados e o apoio integrado são os motivos de seleção. As teclas Mech-Dome não devem ser confundidas com switches mecânicos individuais.', 'O tamanho completo ocupa mais mesa. Evite se precisa de teclado compacto, sem fio ou de switches mecânicos substituíveis.', 'Compare com teclados ABNT2 que atendam seu espaço e tipo de tecla. A iluminação só justifica preço extra se tiver utilidade ou valor para você.', None),
'B0BHMLWH3Z':('g240','mousepads','Para uma superfície de tecido compacta','Quem tem espaço para um mousepad de 340 × 280 mm e prefere tecido a uma superfície rígida.', 'A superfície de tecido e a base de borracha oferecem um ponto de partida definido. A área útil é mais importante que a promessa de combinar com uma marca de sensor.', 'Movimentos amplos em baixa sensibilidade podem exigir um pad maior. A espessura de 1 mm oferece pouca altura de acolchoamento.', 'Meça a área de movimento antes de pagar pelo produto. Um pad do tamanho errado continua inadequado mesmo com desconto.', None),
'B07XLML2YS':('tapo-c200','cameras','Para acompanhar um ambiente em Full HD','Quem precisa de uma câmera interna com rotação e áudio bidirecional.', 'A C200 cobre o recorte de monitoramento interno em 1080p. A rotação permite mudar o enquadramento; não significa ver todas as direções ao mesmo tempo.', 'Não a escolha para exposição externa sem proteção apropriada. Confirme revisão do hardware, opções de gravação e custos de armazenamento.', 'Compare com a C210. Se a diferença for pequena e mais resolução ajudar na sua cena, a C210 merece atenção; caso contrário, a C200 pode bastar.', 'tapo-c210'),
'B095CLQ1PT':('tapo-c210','cameras','Para mais resolução no monitoramento interno','Quem quer comparar uma câmera de 3 MP com alternativas Full HD.', 'A resolução documentada é o avanço concreto sobre a C200 nesta seleção. Mais pixels não garantem melhor identificação em toda iluminação ou distância.', 'O alcance e o resultado dependem da instalação. Confira a versão entregue e não trate a câmera interna como modelo externo.', 'Pague a diferença sobre a C200 quando o detalhe adicional for útil na área observada. Inclua cartão ou serviço de armazenamento no custo.', 'tapo-c200'),
'B08GDC99PX':('tapo-l530e','iluminacao','Para luz ajustável em um soquete E27','Quem quer controlar cor e brilho de uma lâmpada pelo aplicativo, sem hub adicional.', 'Ela concentra a mudança na lâmpada: cores, brilho e comandos compatíveis. Isso pode simplificar uma instalação quando o soquete E27 e a rede atendem.', 'Confira alimentação e espaço na luminária. O interruptor precisa permitir que a lâmpada continue alimentada para receber comandos.', 'Uma única lâmpada pode resolver um ponto de luz. Compare com fita LED apenas se o objetivo for luz indireta distribuída; são usos diferentes.', 'tapo-l920'),
'B09CW3VLBX':('archer-c6','rede','Para rede dual band com portas Gigabit','Quem quer um roteador ou ponto de acesso e consegue posicioná-lo para atender a área necessária.', 'As portas Gigabit e os modos de operação são critérios documentados. A seleção não promete cobertura para qualquer casa nem melhora automática na conexão da operadora.', 'Paredes, posição e interferência mudam o resultado. Confira a revisão de hardware; não escolha por uma soma teórica de velocidades.', 'Antes de comprar mais equipamentos, teste uma posição melhor e conexão por cabo. Compare com Deco quando a necessidade for expansão com múltiplos pontos.', 'deco-m4'),
'B07L44RHC2':('deco-m4','rede','Para começar ou ampliar uma rede Deco','Quem procura uma unidade Deco M4 para uma instalação compatível.', 'Este anúncio é de uma unidade. A proposta expansível permite adicionar outros pontos compatíveis, mas uma unidade sozinha não oferece a cobertura de um kit distribuído.', 'Não compre supondo que receberá duas ou três unidades. Planeje posição e conexão entre os pontos antes de esperar melhora de cobertura.', 'Compare o preço por unidade e o valor de kits completos. Se você já sabe que precisa de vários pontos, o anúncio unitário pode não ser o melhor custo total.', 'archer-c6'),
'B09FSTVWFF':('tapo-l920','iluminacao','Para iluminação indireta de cinco metros','Quem quer efeitos de cor ao longo de uma superfície, como atrás da mesa ou em uma estante.', 'A fita RGB endereçável atende a um papel diferente de uma lâmpada central. Seu benefício é a distribuição da iluminação e os efeitos configuráveis.', 'Meça o percurso e confira instalação, alimentação e instruções de corte. Não a trate como substituta automática de iluminação de trabalho.', 'Pague pela extensão e pelos efeitos que você realmente vai usar. Para um único ponto de luz no teto ou abajur, a L530E pode fazer mais sentido.', 'tapo-l530e'),
'B09WXVH7WK':('echo-pop','assistentes','Para começar com comandos Alexa','Quem quer um speaker compacto para comandos, timers e música em uma rotina simples.', 'A seleção prioriza o acesso à Alexa e o controle de dispositivos compatíveis. Não afirmamos superioridade sonora nem resultado igual em qualquer tamanho de ambiente.', 'Confira os serviços e dispositivos que pretende usar. O acesso por voz não garante compatibilidade universal com todo aparelho inteligente.', 'Compare o preço final com o Echo Dot. Se você não vai usar os recursos adicionais do Dot, o Pop pode atender com menor gasto.', 'echo-dot'),
'B09B8VGCR8':('echo-dot','assistentes','Para rotinas com sensor de temperatura','Quem quer comandos Alexa e vê utilidade em automatizações compatíveis baseadas em temperatura.', 'O sensor interno é um motivo concreto para compará-lo com o Echo Pop. Uma rotina precisa de dispositivos compatíveis para executar a ação desejada.', 'Não o confunda com um controlador universal de qualquer eletrodoméstico. Sensor e comando por voz não substituem a compatibilidade do conjunto.', 'O adicional sobre o Pop faz sentido se o sensor e os outros recursos entrarem no seu uso. Comprar por uma função que ficará desativada reduz o valor da escolha.', 'echo-pop'),
'B0FLYFQL5M':('positivo-ir','controles','Para reunir comandos infravermelhos','Quem quer controlar aparelhos com infravermelho, como uma TV compatível, pelo aplicativo ou assistente.', 'Ele envia comandos infravermelhos; sua função é diferente da tomada que corta energia. A seleção atende quem precisa de comandos como ligar, volume ou modos compatíveis.', 'Confira o suporte ao modelo do aparelho e o alcance no ambiente. Infravermelho não atravessa paredes; planeje a posição e siga a orientação do fabricante.', 'Compare o custo por ambiente. Uma unidade não deve ser comprada esperando controlar todos os cômodos, e um aparelho já inteligente pode dispensar esse acessório.', 'smart-plug-max'),
'B08KFL3SFV':('solocast','microfones','Para começar com um microfone USB','Quem grava voz sozinho e quer conexão ao computador com controle de mute acessível.', 'O padrão cardioide e o sensor de mute atendem a uma rotina individual simples. Posicionamento e acústica continuam influenciando o resultado; não prometemos eliminar o ruído da sala.', 'Não é uma solução XLR para uma interface de áudio. Confira conexão, suporte e distância da boca antes de atribuir o resultado apenas ao microfone.', 'Compare com o AM8 se pretende adotar uma interface no futuro. Para uso somente USB, recursos adicionais precisam justificar o aumento de preço.', 'fifine-am8'),
'B0BMFQP2ZZ':('fifine-am8','microfones','Para começar em USB e considerar XLR','Quem quer um microfone dinâmico com duas rotas de conexão.', 'USB permite uso direto em um computador compatível; XLR abre uma rota com interface de áudio. Essa flexibilidade é o diferencial da seleção, sem promessa de som superior em todo ambiente.', 'Interface e cabo XLR devem entrar no planejamento. Mute, RGB e controles do microfone não funcionam da mesma forma em XLR; confira o manual.', 'O adicional compensa se você vai usar a flexibilidade de conexão. Se ficar apenas no USB básico, compare o custo com o SoloCast.', 'solocast'),
'B0DG9X4WHW':('quadcast-2s','microfones','Para padrões de captação e iluminação configurável','Quem cria conteúdo com cenários de captação variados e valoriza a personalização visual.', 'Os quatro padrões polares ampliam as configurações de uso. A iluminação e a resolução digital são recursos, mas não provam que sua transmissão terá áudio melhor que com uma opção mais simples.', 'Não escolha apenas pelo número de bits ou kHz. Plataforma, configuração e ambiente limitam o benefício audível; ainda é necessário posicionar o microfone corretamente.', 'Compare com o QuadCast 2: se você não precisa da personalização adicional, a diferença de preço pode render mais em suporte ou tratamento do ambiente.', 'quadcast-2'),
'B0D9MCK4R8':('quadcast-2','microfones','Para alternar padrões de captação em USB','Quem precisa mudar a captação conforme grava sozinho ou com outras pessoas.', 'Os quatro padrões e o controle no próprio microfone ajudam a adaptar a operação. Padrão selecionável não elimina ecos nem substitui o posicionamento adequado.', 'Para uma única voz em posição estável, parte dessa flexibilidade pode ficar sem uso. Verifique as conexões e os controles de monitoração necessários.', 'Faz sentido frente ao 2 S quando você quer os padrões de captação sem pagar pela personalização adicional. Compare também com opções USB mais simples.', 'quadcast-2s'),
'B0FFTFYGLV':('elgato-4ks','captura','Para capturar uma fonte HDMI compatível','Quem precisa levar vídeo de um console ou outra fonte HDMI compatível para uma gravação no computador.', 'A função é capturar vídeo externo; a ficha informa captura de até 4K60. Resolução disponível depende do sinal, da conexão e dos requisitos do computador e do software.', 'Não resolve gargalo de um computador que já grava seu próprio jogo. Confira os requisitos completos, modos HDR/VRR e restrições da fonte antes da compra.', 'Só inclua a placa quando houver uma fonte externa para capturar. Para começar transmitindo no mesmo PC, ela pode ser um gasto desnecessário.', None),
'B07DYRS1WH':('stream-deck-mini','controles','Para poucos atalhos físicos frequentes','Quem quer seis teclas LCD para ações recorrentes em programas compatíveis.', 'As teclas identificáveis podem reduzir a procura por comandos. O benefício depende de configurar ações que você realmente repete; o aparelho não automatiza sozinho a produção.', 'Se precisa de muitas ações visíveis ao mesmo tempo, seis teclas podem exigir mudanças de página. Confira compatibilidade de sistema e integrações.', 'Compare com atalhos de teclado que você já usa. O Mini faz sentido quando poucas ações físicas resolvem a rotina e custa menos que o MK.2.', 'stream-deck-mk2'),
'B09738CV2G':('stream-deck-mk2','controles','Para quinze comandos à vista','Quem trabalha com mais ações frequentes e quer reduzir a troca entre páginas de atalhos.', 'As 15 teclas oferecem acesso simultâneo a mais comandos que o Mini. Esse é o ganho central; a seleção não pressupõe aumento de produtividade sem configuração e uso recorrente.', 'Ocupa espaço e exige definir suas ações. Não compre esperando corrigir limitações de áudio, vídeo ou desempenho do computador.', 'O adicional sobre o Mini compensa quando seis teclas são uma limitação real. Se seu fluxo usa poucas ações, comece pela opção mais simples.', 'stream-deck-mini'),
'B0B8GRCXB6':('wave-dx','microfones','Para quem já planeja uma cadeia XLR','Quem usa ou pretende montar interface, cabo e suporte para um microfone dinâmico.', 'A conexão XLR permite integrá-lo a uma cadeia de áudio compatível. A comparação com um USB precisa considerar o sistema completo, não apenas o preço do microfone.', 'Não conecta diretamente a uma porta USB. Interface de áudio, cabo XLR e suporte ou braço são necessários para o uso planejado.', 'Faz mais sentido se você já tem os acessórios adequados. Para começar do zero com orçamento restrito, compare o custo completo com SoloCast ou AM8.', 'fifine-am8'),
}

for niche, filename in [('setup-games','games'),('casa-inteligente','home'),('creator-streaming','creator')]:
    evidence=json.loads((ROOT/f'docs/catalogo/{filename}-sources-20260908.json').read_text())
    for p in evidence['products']:
        asin=p['asin']
        if asin=='B0BNSVWWDR':
            original=next(x for x in catalog['products'] if x['asin']==asin)
            original['image']=p['image']
            original['source']=p['manufacturer']
            original['evidence']=f'docs/catalogo/{filename}-sources-20260908.json'
            continue
        if asin in {x['asin'] for x in catalog['products']}:
            original=next(x for x in catalog['products'] if x['asin']==asin)
            original['image']=p.get('image',p.get('imageUrl',p.get('observedImageUrl')))
            continue
        ident,group,role,fit,reason,avoid,value,alternative=COPY[asin]
        specs=p.get('facts',p.get('manufacturerFacts',p.get('verifiedSpecs',[])))[:3]
        if filename=='creator':
            specs={
                'solocast':['Conexão USB','Padrão cardioide','Sensor de mute'],
                'fifine-am8':['Microfone dinâmico cardioide','USB e XLR','Confira recursos disponíveis em cada conexão'],
                'quadcast-2s':['Quatro padrões polares','USB-C e saída de fones','Iluminação aRGB configurável'],
                'quadcast-2':['Quatro padrões polares','USB-C e saída de fones','Controle de mute e botão multifunção'],
                'elgato-4ks':['Captura de até 4K60','USB-C 3.2 Gen 1','Entrada e saída HDMI 2.0'],
                'stream-deck-mini':['6 teclas LCD configuráveis','Modelo 10GAI9901','Verifique sistema e integrações'],
                'stream-deck-mk2':['15 teclas LCD configuráveis','Versão MK.2 preta','Integrações com programas compatíveis'],
                'wave-dx':['Microfone dinâmico cardioide','Conexão XLR','Exige interface, cabo e suporte'],
            }[ident]
        catalog['products'].append(dict(id=ident,niche=niche,group=group,name=p['name'],asin=asin,variant=p['variant'],image=p.get('image',p.get('imageUrl',p.get('observedImageUrl'))),status='published',role=role,fit=fit,specs=specs,reason=reason,avoid=avoid,value=value,alternative=alternative,source=p.get('manufacturer',p.get('manufacturerSpecUrl')),evidence=f'docs/catalogo/{filename}-sources-20260908.json'))
WORK={
 'B00V4BGD00':('uh400','hubs','Para ampliar portas USB-A','Quem precisa conectar mais periféricos USB-A a um computador compatível.', ['4 portas USB 3.0','Conexão ao computador por USB-A','Modelo UH400 preto'], 'O UH400 atende a expansão de portas de dados. Essa função é mais simples que a de um hub USB-C com vídeo e passagem de energia.', 'Não acrescenta saída HDMI nem carregamento USB-C do notebook. Confira a demanda de energia dos periféricos e a porta disponível.', 'Se faltam apenas portas USB-A, compare seu custo com soluções mais complexas. Não pague por HDMI ou carregamento de que você não precisa.', 'anker-332'),
 'B000UXZQ42':('h390','headsets','Para chamadas com conexão USB-A','Quem quer headset com fio e controles de áudio para reuniões no computador.', ['USB-A com fio','Controles de áudio no cabo','Microfone com redução de ruído declarada'], 'A conexão USB e os controles acessíveis definem o uso de trabalho. A redução de ruído do microfone é um recurso declarado; não apresentamos uma medição própria de inteligibilidade.', 'Esta é a versão USB-A, não a USB-C. Não serve diretamente a um conector analógico 3,5 mm; confira as portas do seu aparelho.', 'Pagar por um headset dedicado faz sentido quando o áudio das reuniões é uma limitação. Compare com um equipamento que você já possui antes de duplicar funções.', None),
 'B0BQLLB61B':('anker-332','hubs','Para vídeo e periféricos por USB-C','Quem tem um notebook com USB-C compatível com as funções de vídeo e energia desejadas.', ['Hub USB-C 5 em 1','HDMI até 4K a 30 Hz','Portas USB para dados e entrada de energia PD'], 'Ele reúne funções que um hub USB-A comum não oferece. A saída HDMI depende de suporte de vídeo na porta USB-C do computador; o formato do conector, sozinho, não garante isso.', 'Não trate 4K30 como 4K60. Carregador, cabo e capacidade da porta limitam a alimentação; confira requisitos e acessórios incluídos.', 'Some o carregador adequado se for necessário. Se você precisa somente de mais USB-A, o UH400 é a comparação mais simples; se precisa de vídeo, compare hubs com a frequência desejada.', 'uh400'),
 'B0C5JQ68FY':('sandisk-portable','armazenamento','Para transportar arquivos em SSD externo','Quem precisa de armazenamento portátil sem instalar uma unidade dentro do computador.', ['1 TB','SSD externo USB-C','Modelo SDSSDE30-1T00-G26'], 'O uso externo é o critério central. O teto de velocidade anunciado depende do dispositivo e da conexão; não representa desempenho sustentado garantido em qualquer transferência.', 'Não confunda este modelo Portable com outras linhas SanDisk. Mantenha outra cópia dos arquivos importantes: uma unidade portátil não elimina o risco de perda.', 'Compare capacidade útil para seus arquivos, conexão e garantia do anúncio. Um SSD interno pode custar menos, mas não substitui a portabilidade sem outros acessórios.', 'kingston-a400'),
 'B01N0TQPQB':('kingston-a400','armazenamento','Para um upgrade interno SATA compatível','Quem tem computador com espaço e conexão para SSD SATA de 2,5 polegadas.', ['480 GB','SATA de 2,5 polegadas','Modelo SA400S37/480G'], 'A proposta é armazenamento interno para uma máquina compatível. A troca de um disco mecânico pode mudar a resposta do sistema, mas a instalação e a migração de dados fazem parte do trabalho.', 'Não é SSD M.2 NVMe e não encaixa em um slot M.2. Confira espaço, cabo ou adaptador necessário antes de comprar.', 'Inclua instalação e migração se precisar de ajuda. Para apenas transportar arquivos entre máquinas, compare com um SSD externo pronto para esse uso.', 'sandisk-portable'),
 'B0BX1PWTZ2':('brio-300','webcams','Para chamadas com USB-C','Quem quer webcam Full HD e possui uma porta USB-C disponível no computador.', ['Full HD','Conexão USB-C','Proteção física de privacidade'], 'O conector USB-C e o obturador são características úteis para uma mesa de trabalho compatível. A correção automática de luz não substitui iluminação adequada.', 'Confirme que o enquadramento e os recursos de foco atendem sua rotina. USB-C por si só não garante vídeo melhor que uma webcam USB-A.', 'Compare o preço completo com Brio 100 e C920s, incluindo adaptador quando necessário. Pague pela conexão e pelos recursos úteis, não pelo nome de uma série maior.', 'brio-100'),
 'B0CH9WTW56':('arzopa-z1fc','monitores','Para levar uma segunda tela','Quem alterna locais de trabalho e quer mais área de tela em um formato portátil.', ['16,1 polegadas Full HD','Até 144 Hz declarados','Modelo Z1FC'], 'A portabilidade e a segunda área de trabalho explicam sua presença no nicho. Para documentos, o tamanho útil e o apoio podem importar mais que a frequência máxima anunciada.', 'Confira vídeo e alimentação disponíveis no notebook, cabos e posição do apoio. Uma tela portátil não oferece a mesma área e ergonomia de um monitor de mesa maior.', 'O custo extra se justifica se você realmente precisa transportar a tela. Para uso fixo, compare monitores de mesa e a ergonomia do conjunto.', 'lg-24gs60f'),
 'B0CJ3WFW9H':('k380s','teclados','Para alternar dispositivos em pouco espaço','Quem procura teclado Bluetooth compacto e aceita layout americano.', ['Bluetooth com Easy-Switch','Layout US, cor grafite','Pilha incluída no anúncio'], 'O formato compacto e a troca entre dispositivos atendem quem alterna trabalho e mobilidade. A versão selecionada é US: essa diferença afeta a posição dos símbolos e o hábito de digitação.', 'Não é ABNT2 e não possui tecla Ç dedicada como um teclado brasileiro. Confira o layout e os sistemas compatíveis antes de comparar só o tamanho.', 'Pague pela portabilidade e pela troca de aparelhos se essas funções forem frequentes. Para uso fixo com ABNT2 indispensável, procure uma opção no layout adequado.', 'g213'),
 'B09HM94VDS':('mx-master-3s','mouses','Para rolagem e atalhos no trabalho','Quem passa muitas horas em documentos ou planilhas e quer controles adicionais no mouse.', ['Bluetooth e receptor Logi Bolt','Edição padrão grafite','Rolagem rápida e recarga USB-C'], 'Rolagem e controles programáveis são o motivo desta seleção. A forma da carcaça exige adaptação individual; o rótulo ergonômico não garante conforto para todas as mãos.', 'Não o escolha como substituto automático de um mouse leve para jogo competitivo. Confira tamanho, pegada e compatibilidade do software com suas funções desejadas.', 'O valor depende de usar rolagem e atalhos diariamente. Se você só precisa mover o cursor e clicar, compare uma opção mais simples antes de pagar o adicional.', 'g305'),
}
evidence=json.loads((ROOT/'docs/catalogo/work-sources-20260908.json').read_text())
for p in evidence['products']:
    if p['asin'] in {x['asin'] for x in catalog['products']}: continue
    ident,group,role,fit,specs,reason,avoid,value,alternative=WORK[p['asin']]
    official=[u for u in p['identitySources'] if 'amazon.' not in u and 'instagram.' not in u]
    source=official[0] if official else p['amazonBrUrl']
    catalog['products'].append(dict(id=ident,niche='trabalho-estudo',group=group,name=p['name'],asin=p['asin'],variant=p['variant'],image=p['imageUrl'],status='published',role=role,fit=fit,specs=specs,reason=reason,avoid=avoid,value=value,alternative=alternative,source=source,evidence='docs/catalogo/work-sources-20260908.json'))
PORTUGUESE_VARIANTS={
 'B08KFL3SFV':'SoloCast preto, conexão USB',
 'B0BMFQP2ZZ':'AM8 preto, base e cabo USB',
 'B0DG9X4WHW':'QuadCast 2 S preto',
 'B0D9MCK4R8':'QuadCast 2 preto',
 'B0FFTFYGLV':'Game Capture 4K S preto, 10GBR9901',
 'B07DYRS1WH':'Mini preto, seis teclas LCD, 10GAI9901',
 'B09738CV2G':'MK.2 preto, quinze teclas LCD, 10GBA9901',
 'B0B8GRCXB6':'Wave DX dinâmico XLR, preto, 10MAH9901',
 'B000UXZQ42':'H390 preto, USB-A',
 'B0CJ3WFW9H':'Pebble Keys 2 K380s grafite, layout US',
 'B09HM94VDS':'MX Master 3S grafite, edição padrão com receptor Logi Bolt',
}
for p in catalog['products']:
    if p['asin'] in PORTUGUESE_VARIANTS: p['variant']=PORTUGUESE_VARIANTS[p['asin']]
    if p['id']=='havit-h2002d': p['source']='https://havitsmart.com/products/h2002d-3-5mm-gaming-headphone'
(ROOT/'data/catalogo-curado.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
print(f'Editorial import complete: {len(catalog["products"])} selected products. Not deployed.')
